### ISSUE TITLE
examble

### ISSUE THREAD

**Issue by printetrain** [adamz0210/NodeRed_Niagara_Obix_Node#1]
Hi, i have found your Project and tested it but i didn´t  become values   from my station. Can you give me some examble about the watcher

regards

Wolfgang from Germany

**Comment by adumnov** [comment]
Unfortunately I also can't get any values from Niagara 3.8 OBIX to node-red via node-red-contrib-obix... Even there is no any messages about connections from node-red in the http-log on Niagara.
But I successfully connected via Obix protocol from my own javascript.
Any idea about contrib problems? HttpAuth sceme is Basic, SSLv3&TLSv1 was enabled in Niagara.

**Comment by adumnov** [comment]
> 
> Unfortunately I also can't get any values from Niagara 3.8 OBIX to node-red via node-red-contrib-obix... Even there is no any messages about connections from node-red in the http-log on Niagara.
> But I successfully connected via Obix protocol from my own javascript.
> Any idea about contrib problems? HttpAuth sceme is Basic, SSLv3&TLSv1 was enabled in Niagara.

I've change the connection to Niagara from HTTPS to HTTP (into the contrib code) and successfully set the connection and get values. It's due to TLSv1 of Niagara 3.8 unsupported in Node-red.

Please, could you deploy a version of the contrib with a choosing of connection method (HTTP or HTTPS). Thanks in advance!

**Comment by adamz0210** [comment]
> > Unfortunately I also can't get any values from Niagara 3.8 OBIX to node-red via node-red-contrib-obix... Even there is no any messages about connections from node-red in the http-log on Niagara.
> > But I successfully connected via Obix protocol from my own javascript.
> > Any idea about contrib problems? HttpAuth sceme is Basic, SSLv3&TLSv1 was enabled in Niagara.
> 
> I've change the connection to Niagara from HTTPS to HTTP (into the contrib code) and successfully set the connection and get values. It's due to TLSv1 of Niagara 3.8 unsupported in Node-red.
> 
> Please, could you deploy a version of the contrib with a choosing of connection method (HTTP or HTTPS). Thanks in advance!

I have added this functionality and pushed the new version to the node-red library... Thank you for the feedback

**Comment by adamz0210** [comment]
> Hi, i have found your Project and tested it but i didn´t become values from my station. Can you give me some examble about the watcher
> 
> regards
> 
> Wolfgang from Germany



![image](https://user-images.githubusercontent.com/64041152/105103221-3a92a400-5a7e-11eb-8162-7453aedd3b35.png)

![image](https://user-images.githubusercontent.com/64041152/105103611-dcb28c00-5a7e-11eb-95e7-0ed9cebaed06.png)


Here is an example of a point path. It doesn't create values in your station, it only reads/writes from existing ones... Hope this helped

**Comment by Julian-Featherston** [comment]
Hi adamzman

Thank you for your work on this project!
We are looking to use NodeRed_Niagara_Obix_Node as part of a climate-tech startup working on large building predictive HVAC control. I'd love to chat about your experience with oBIX strengths and weakness's and and where we might contribute to the Obix_Node project. If that's a possibility please drop me a message at julian@halsystems.com.au

Best
Julian
